apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: io69j4rca-python-gitops
  description: This is GitOps manifest for io69j4rca-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=io69j4rca-python
    backstage.io/kubernetes-id: io69j4rca-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: io69j4rca-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:io69j4rca-python
