apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: io69j4rca-python
  janus-idp.io/tekton: io69j4rca-python
  backstage.io/kubernetes-id: io69j4rca-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: io69j4rca-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
